import type { Lesson } from "../types";

export const foundations: Lesson[] = [
  {
    id: "ia-cest-quoi",
    title: "L'IA, c'est quoi au juste ?",
    objective: "Faire la différence entre un programme classique et une IA qui apprend à partir d'exemples.",
    level: 1,
    durationMin: 5,
    xp: 20,
    skills: ["Distinguer IA et programme classique", "Reconnaître l'IA au quotidien"],
    prerequisites: [],
    blocks: [
      {
        type: "text",
        title: "Des règles ou des exemples",
        body: "Un programme classique suit des règles écrites à la main par un humain : « si le mail contient tel mot, mets-le dans les spams ». Une IA fonctionne autrement : on lui montre des millions d'exemples (des mails marqués spam ou non) et elle repère elle-même les régularités qui les distinguent.",
      },
      {
        type: "illustration",
        id: "rules-vs-examples",
        caption: "À gauche, un humain écrit les règles. À droite, la machine les déduit des exemples.",
      },
      {
        type: "text",
        title: "Tu en utilises déjà",
        body: "Le filtre anti-spam, les suggestions de vidéos, la traduction automatique, la reconnaissance de visage de ton téléphone : ce sont des IA. Les assistants comme ChatGPT ou Claude sont une famille particulière, l'IA générative : elle produit du nouveau contenu (texte, image, son) au lieu de simplement classer ou recommander.",
      },
      {
        type: "keypoint",
        body: "Une IA ne comprend pas le monde comme toi. Elle repère des régularités statistiques dans des données, souvent avec une efficacité impressionnante.",
      },
    ],
    questions: [
      {
        id: "ia-cest-quoi:q1",
        type: "mcq",
        prompt: "Qu'est-ce qui distingue une IA d'un programme classique ?",
        options: [
          { id: "a", text: "Elle est toujours plus rapide", feedback: "Pas forcément : un programme classique est souvent plus rapide." },
          { id: "b", text: "Elle déduit des régularités à partir d'exemples" },
          { id: "c", text: "Elle a une conscience", feedback: "Non. Rien n'indique qu'une IA actuelle ait une conscience." },
          { id: "d", text: "Elle est forcément connectée à Internet", feedback: "Beaucoup d'IA fonctionnent hors ligne, sur ton téléphone par exemple." },
        ],
        answer: "b",
        explanation: "Au lieu de suivre seulement des règles écrites à la main, une IA apprend des régularités à partir d'un grand nombre d'exemples.",
      },
      {
        id: "ia-cest-quoi:q2",
        type: "true_false",
        statement: "Un filtre anti-spam peut être une IA.",
        answer: true,
        explanation: "Oui : la plupart des filtres modernes apprennent à reconnaître les spams à partir de millions de mails déjà classés.",
      },
      {
        id: "ia-cest-quoi:q3",
        type: "fill_choice",
        prompt: "Complète la phrase.",
        sentence: "Une IA générative ___ du nouveau contenu : texte, image ou son.",
        options: [
          { id: "a", text: "produit" },
          { id: "b", text: "recopie toujours" },
          { id: "c", text: "se contente de classer" },
        ],
        answer: "a",
        explanation: "« Générative » veut dire qu'elle génère, c'est-à-dire produit, du contenu nouveau.",
      },
      {
        id: "ia-cest-quoi:q4",
        type: "ordering",
        prompt: "Remets dans l'ordre les étapes de création d'une IA.",
        items: [
          { id: "a", text: "Rassembler beaucoup d'exemples" },
          { id: "b", text: "Entraîner le modèle sur ces exemples" },
          { id: "c", text: "Le tester sur des exemples qu'il n'a jamais vus" },
          { id: "d", text: "L'utiliser dans une application" },
        ],
        answer: ["a", "b", "c", "d"],
        explanation: "Données, entraînement, test sur des cas nouveaux, puis mise en service. Le test sur des cas inédits vérifie qu'elle n'a pas juste « appris par cœur ».",
      },
      {
        id: "ia-cest-quoi:q5",
        type: "true_false",
        statement: "Une IA comprend le sens des mots exactement comme un humain.",
        answer: false,
        explanation: "Elle manipule des régularités statistiques. Le résultat peut ressembler à de la compréhension, mais le mécanisme est très différent.",
      },
    ],
  },
  {
    id: "comment-ecrit-un-chatbot",
    title: "Comment un chatbot écrit ses réponses",
    objective: "Comprendre qu'un assistant IA prédit la suite d'un texte, morceau par morceau.",
    level: 1,
    durationMin: 6,
    xp: 20,
    skills: ["Expliquer la prédiction du mot suivant", "Savoir ce qu'est un token"],
    prerequisites: ["ia-cest-quoi"],
    blocks: [
      {
        type: "text",
        title: "Un très grand modèle de langage",
        body: "ChatGPT, Claude ou Gemini reposent sur un « grand modèle de langage » (LLM). Il a été entraîné sur une quantité énorme de textes. Son talent principal : à partir d'un début de texte, estimer quel morceau de texte a le plus de chances de venir ensuite.",
      },
      {
        type: "illustration",
        id: "next-token",
        caption: "Le modèle attribue une probabilité à chaque suite possible, en choisit une, puis recommence.",
      },
      {
        type: "text",
        title: "Des tokens, pas des mots",
        body: "Le modèle ne lit pas des mots mais des « tokens » : des morceaux de texte. « Incroyable » peut être découpé en « In », « croy », « able ». Ta question est découpée en tokens, le modèle prédit le token suivant, l'ajoute, et recommence, des centaines de fois. C'est pour ça que la réponse s'affiche petit à petit.",
      },
      {
        type: "example",
        label: "Exemple de prédiction",
        content: "« Le chat dort sur le… » → canapé (41 %), lit (23 %), toit (9 %), clavier (6 %)…",
      },
      {
        type: "text",
        title: "Une part de hasard",
        body: "Le modèle ne choisit pas toujours la suite la plus probable : une petite part de hasard rend les réponses plus naturelles. Résultat : la même question peut donner deux réponses différentes.",
      },
      {
        type: "keypoint",
        body: "Probable ne veut pas dire vrai. Le modèle produit ce qui sonne juste, pas ce qu'il a vérifié.",
      },
    ],
    questions: [
      {
        id: "comment-ecrit-un-chatbot:q1",
        type: "mcq",
        prompt: "À chaque étape, un modèle de langage…",
        options: [
          { id: "a", text: "prédit le morceau de texte suivant le plus plausible" },
          { id: "b", text: "cherche la réponse dans une encyclopédie", feedback: "Certains outils peuvent consulter le web, mais le cœur du modèle prédit du texte." },
          { id: "c", text: "copie une page web existante", feedback: "Il génère un texte nouveau, token par token." },
          { id: "d", text: "fait relire sa réponse par un humain", feedback: "Non, la réponse est générée automatiquement." },
        ],
        answer: "a",
        explanation: "Un LLM génère sa réponse en prédisant la suite du texte, un token après l'autre.",
      },
      {
        id: "comment-ecrit-un-chatbot:q2",
        type: "true_false",
        statement: "Si tu poses deux fois la même question, tu peux obtenir deux réponses différentes.",
        answer: true,
        explanation: "Une part de hasard contrôlé intervient dans le choix des tokens. Les réponses varient d'une fois sur l'autre.",
      },
      {
        id: "comment-ecrit-un-chatbot:q3",
        type: "fill_choice",
        prompt: "Complète la phrase.",
        sentence: "Pour un modèle de langage, « probable » ne veut pas dire ___.",
        options: [
          { id: "a", text: "vrai" },
          { id: "b", text: "long" },
          { id: "c", text: "rapide" },
        ],
        answer: "a",
        explanation: "Le modèle optimise la plausibilité du texte, pas sa vérité. C'est la racine des hallucinations.",
      },
      {
        id: "comment-ecrit-un-chatbot:q4",
        type: "ordering",
        prompt: "Que se passe-t-il quand tu envoies un message ? Remets dans l'ordre.",
        items: [
          { id: "a", text: "Ton texte est découpé en tokens" },
          { id: "b", text: "Le modèle calcule les suites probables" },
          { id: "c", text: "Il choisit un token, l'ajoute et recommence" },
          { id: "d", text: "La réponse s'affiche petit à petit" },
        ],
        answer: ["a", "b", "c", "d"],
        explanation: "Découpage en tokens, prédiction, choix, et ainsi de suite jusqu'à la fin de la réponse.",
      },
      {
        id: "comment-ecrit-un-chatbot:q5",
        type: "mcq",
        prompt: "Un « token », c'est…",
        options: [
          { id: "a", text: "un morceau de texte : un mot ou un bout de mot" },
          { id: "b", text: "un mot de passe", feedback: "Rien à voir ici avec la sécurité." },
          { id: "c", text: "une image", feedback: "Non, dans un modèle de langage il s'agit de texte." },
        ],
        answer: "a",
        explanation: "Les modèles découpent le texte en tokens, souvent plus petits qu'un mot.",
      },
    ],
  },
  {
    id: "hallucinations",
    title: "Les hallucinations : quand l'IA invente",
    objective: "Repérer une information inventée et savoir quoi vérifier en priorité.",
    level: 1,
    durationMin: 6,
    xp: 25,
    skills: ["Repérer une hallucination", "Vérifier une affirmation"],
    prerequisites: ["comment-ecrit-un-chatbot"],
    blocks: [
      {
        type: "text",
        title: "Faux, mais sûr de lui",
        body: "Une hallucination, c'est une information fausse ou inventée, présentée avec assurance. Ce n'est pas un bug rare : c'est une conséquence directe du fonctionnement du modèle, qui produit du texte plausible.",
      },
      {
        type: "illustration",
        id: "hallucination",
        caption: "Ce qui est plausible et ce qui est vrai se recouvrent souvent, mais pas toujours.",
      },
      {
        type: "example",
        label: "Une référence inventée",
        good: false,
        content: "« Selon l'étude de Martin & Lopez (2019), publiée dans Nature, 73 % des adolescents… » L'étude, les auteurs et le chiffre peuvent être entièrement inventés, avec une forme parfaite.",
      },
      {
        type: "text",
        title: "Les zones à risque",
        body: "Chiffres précis, citations, références bibliographiques, événements récents, personnes ou entreprises peu connues, lois et articles de loi. Plus la demande est pointue, plus le modèle risque de combler les trous.",
      },
      {
        type: "keypoint",
        body: "Plus une information est précise et importante pour toi, plus tu dois la vérifier dans une source fiable.",
      },
    ],
    questions: [
      {
        id: "hallucinations:q1",
        type: "true_false",
        statement: "Une IA qui répond avec assurance a forcément raison.",
        answer: false,
        explanation: "Le ton est toujours assuré, même quand le contenu est inventé. L'assurance n'est pas une preuve.",
      },
      {
        id: "hallucinations:q2",
        type: "ranking",
        prompt: "Classe ces demandes selon le risque d'hallucination.",
        scale: ["Risque le plus élevé", "Risque le plus faible"],
        items: [
          { id: "a", text: "Donne-moi 3 articles scientifiques avec leurs références exactes" },
          { id: "b", text: "Explique-moi la photosynthèse en gros" },
          { id: "c", text: "Résume ce texte que je te colle" },
        ],
        answer: ["a", "b", "c"],
        explanation: "Les références exactes sont le terrain favori des inventions. Une explication générale est plus sûre. Résumer un texte fourni est le moins risqué, même s'il faut relire.",
      },
      {
        id: "hallucinations:q3",
        type: "ai_analysis",
        prompt: "Lis l'échange. Qu'est-ce qui pose problème ? Sélectionne tout ce qui s'applique.",
        userMessage: "Donne-moi une citation de Victor Hugo sur l'intelligence artificielle.",
        aiResponse: "Bien sûr ! Victor Hugo écrivait en 1862 : « La machine qui pense sera la plus grande conquête de l'homme. » (Les Misérables, tome 3)",
        options: [
          { id: "a", text: "La citation est très probablement inventée" },
          { id: "b", text: "Les détails précis (année, tome) donnent une fausse impression de fiabilité" },
          { id: "c", text: "La réponse est trop courte" },
          { id: "d", text: "Le ton est trop poli" },
        ],
        answer: ["a", "b"],
        explanation: "La notion d'intelligence artificielle n'existait pas du temps de Hugo. Les détails précis rendent l'invention crédible : c'est typique d'une hallucination.",
      },
      {
        id: "hallucinations:q4",
        type: "mcq",
        prompt: "Une IA te donne un chiffre précis pour ton exposé. Le meilleur réflexe ?",
        options: [
          { id: "a", text: "Le vérifier dans une source fiable avant de l'utiliser" },
          { id: "b", text: "Demander à l'IA si elle est sûre, et la croire", feedback: "Elle peut confirmer une erreur avec la même assurance." },
          { id: "c", text: "L'arrondir pour limiter l'erreur", feedback: "Un chiffre inventé reste inventé, même arrondi." },
        ],
        answer: "a",
        explanation: "La vérification se fait hors de l'IA, dans une source qui fait autorité.",
      },
      {
        id: "hallucinations:q5",
        type: "fill_choice",
        prompt: "Complète la définition.",
        sentence: "Une hallucination, c'est une information ___ présentée comme vraie.",
        options: [
          { id: "a", text: "fausse ou inventée" },
          { id: "b", text: "un peu ancienne" },
          { id: "c", text: "trop longue" },
        ],
        answer: "a",
        explanation: "C'est le mélange de fausseté et d'assurance qui rend les hallucinations dangereuses.",
      },
    ],
  },
  {
    id: "vie-privee",
    title: "Protéger tes données",
    objective: "Savoir ce qu'il ne faut jamais taper dans un assistant IA et comment anonymiser.",
    level: 2,
    durationMin: 6,
    xp: 25,
    skills: ["Identifier les données sensibles", "Anonymiser un texte"],
    prerequisites: ["ia-cest-quoi"],
    blocks: [
      {
        type: "text",
        title: "Ce que tu tapes voyage",
        body: "Ton message part sur les serveurs de l'éditeur. Selon le service et tes réglages, il peut être conservé, relu par des humains pour améliorer le service, ou utilisé pour entraîner de futurs modèles.",
      },
      {
        type: "illustration",
        id: "data-flow",
        caption: "Du clavier aux serveurs : chaque étape est un endroit où ton texte peut être conservé.",
      },
      {
        type: "text",
        title: "Jamais dans un chatbot",
        body: "Mots de passe, codes bancaires, numéros de sécurité sociale, données de santé, documents confidentiels, informations privées sur d'autres personnes.",
      },
      {
        type: "example",
        label: "Anonymiser avant de coller",
        good: true,
        content: "« Mon collègue Thomas Durand m'a dit… » devient « Mon collègue (Personne A) m'a dit… ». L'IA peut t'aider tout autant.",
      },
      {
        type: "keypoint",
        body: "Règle simple : n'écris rien que tu ne mettrais pas sur une carte postale.",
      },
    ],
    questions: [
      {
        id: "vie-privee:q1",
        type: "ranking",
        prompt: "Classe ces informations de la plus à la moins sensible.",
        scale: ["La plus sensible", "La moins sensible"],
        items: [
          { id: "a", text: "Le code de ta carte bancaire" },
          { id: "b", text: "Ton adresse personnelle complète" },
          { id: "c", text: "Ta recette de crêpes préférée" },
        ],
        answer: ["a", "b", "c"],
        explanation: "Un code bancaire donne un accès direct à ton argent. Une adresse te localise. Une recette ne risque rien.",
      },
      {
        id: "vie-privee:q2",
        type: "true_false",
        statement: "Remplacer les vrais noms par « Personne A », « Personne B » est un bon réflexe avant de coller un texte.",
        answer: true,
        explanation: "L'anonymisation garde l'utilité du texte pour l'IA tout en protégeant les personnes.",
      },
      {
        id: "vie-privee:q3",
        type: "mcq",
        prompt: "Que faire avant de coller un document dans un assistant IA ?",
        options: [
          { id: "a", text: "Retirer ou remplacer les informations personnelles" },
          { id: "b", text: "Le traduire en anglais", feedback: "La langue ne change rien à la confidentialité." },
          { id: "c", text: "Rien, c'est privé par défaut", feedback: "Pas forcément : cela dépend du service et de tes réglages." },
        ],
        answer: "a",
        explanation: "Retire ce qui identifie quelqu'un ou ce qui est confidentiel. L'IA n'en a presque jamais besoin.",
      },
      {
        id: "vie-privee:q4",
        type: "fill_choice",
        prompt: "Complète la règle.",
        sentence: "N'écris rien que tu ne mettrais pas sur ___.",
        options: [
          { id: "a", text: "une carte postale" },
          { id: "b", text: "ton CV" },
          { id: "c", text: "ton agenda" },
        ],
        answer: "a",
        explanation: "Une carte postale peut être lue par tous ceux qui la manipulent. C'est un bon modèle mental.",
      },
      {
        id: "vie-privee:q5",
        type: "ai_analysis",
        prompt: "Lis l'échange. Qu'est-ce qui pose problème ? Sélectionne tout ce qui s'applique.",
        userMessage: "Voici mon numéro de sécu 1 84 12 75 108 042 37 et mon IBAN FR76 3000 4000 0312 3456 7890 143. Aide-moi à remplir ce formulaire.",
        aiResponse: "Avec plaisir ! Dans la case « N° de sécurité sociale », indique 1 84 12 75 108 042 37, puis…",
        options: [
          { id: "a", text: "Des données très sensibles ont été partagées sans nécessité" },
          { id: "b", text: "L'aide aurait été la même avec des valeurs fictives" },
          { id: "c", text: "L'IA aurait dû répondre en anglais" },
          { id: "d", text: "Il n'y a aucun problème" },
        ],
        answer: ["a", "b"],
        explanation: "Pour expliquer comment remplir un formulaire, des valeurs d'exemple suffisent. Les vraies données n'apportent rien et créent un risque.",
      },
    ],
  },
  {
    id: "panorama-outils",
    title: "ChatGPT, Claude, Gemini, DeepSeek, Perplexity",
    objective: "Connaître les grands assistants, qui les édite, et choisir le bon pour une tâche.",
    level: 3,
    durationMin: 8,
    xp: 30,
    skills: ["Comparer les assistants IA", "Choisir l'outil adapté à une tâche"],
    prerequisites: ["hallucinations"],
    volatile: { toolIds: ["chatgpt", "claude", "gemini", "deepseek", "perplexity"] },
    blocks: [
      {
        type: "text",
        title: "Même moteur, styles différents",
        body: "Ces assistants reposent tous sur des grands modèles de langage. Ce qui les distingue : l'entreprise qui les édite, leurs intégrations, leur accès au web, leur gestion de tes données et leurs points forts.",
      },
      {
        type: "illustration",
        id: "tool-landscape",
        caption: "Cinq assistants placés selon deux usages : converser et créer, ou chercher et vérifier.",
      },
      { type: "tools", toolIds: ["chatgpt", "claude", "gemini", "deepseek", "perplexity"] },
      {
        type: "keypoint",
        body: "Le meilleur outil dépend de la tâche. Et quel que soit l'outil, les réflexes restent les mêmes : vérifier, protéger tes données, relire.",
      },
    ],
    questions: [
      {
        id: "panorama-outils:q1",
        type: "mcq",
        prompt: "Quel outil est conçu d'abord pour chercher sur le web et citer ses sources ?",
        options: [
          { id: "a", text: "Perplexity" },
          { id: "b", text: "DeepSeek", feedback: "DeepSeek est surtout connu pour ses modèles de raisonnement et de code." },
          { id: "c", text: "Claude", feedback: "Claude peut chercher sur le web selon l'offre, mais ce n'est pas son identité principale." },
        ],
        answer: "a",
        explanation: "Perplexity se présente comme un moteur de réponse : recherche web et liens numérotés vers les sources.",
      },
      {
        id: "panorama-outils:q2",
        type: "mcq",
        prompt: "Qui édite Claude ?",
        options: [
          { id: "a", text: "OpenAI" },
          { id: "b", text: "Anthropic" },
          { id: "c", text: "Google" },
          { id: "d", text: "DeepSeek" },
        ],
        answer: "b",
        explanation: "Claude est développé par Anthropic. OpenAI édite ChatGPT, Google édite Gemini.",
      },
      {
        id: "panorama-outils:q3",
        type: "true_false",
        statement: "Les données de l'application DeepSeek sont stockées en Chine selon sa politique de confidentialité : mieux vaut éviter d'y mettre des informations sensibles.",
        answer: true,
        explanation: "C'est précisé dans sa politique de confidentialité, et plusieurs autorités européennes s'y sont intéressées.",
      },
      {
        id: "panorama-outils:q4",
        type: "fill_choice",
        prompt: "Complète la phrase.",
        sentence: "Gemini est l'assistant IA développé par ___.",
        options: [
          { id: "a", text: "Google" },
          { id: "b", text: "Microsoft" },
          { id: "c", text: "Meta" },
        ],
        answer: "a",
        explanation: "Gemini est l'assistant de Google, intégré notamment à Gmail, Docs et Android.",
      },
      {
        id: "panorama-outils:q5",
        type: "true_false",
        statement: "Un outil qui cite ses sources ne peut pas se tromper.",
        answer: false,
        explanation: "Il peut mal résumer une source, ou citer une source peu fiable. Ouvre les liens.",
      },
    ],
  },
];
