import type { Lesson } from "../types";

export const studentLessons: Lesson[] = [
  {
    id: "premier-prompt",
    title: "Écrire une bonne demande",
    objective: "Rédiger une demande claire avec contexte, tâche, format et contraintes, puis l'améliorer.",
    level: 2,
    durationMin: 7,
    xp: 25,
    skills: ["Structurer une demande", "Améliorer une réponse en plusieurs tours"],
    prerequisites: ["comment-ecrit-un-chatbot"],
    blocks: [
      {
        type: "text",
        title: "Le prompt, c'est ta demande",
        body: "L'IA ne connaît ni ta situation, ni ton objectif, ni ce que tu attends. Tout ce que tu ne dis pas, elle le devine, souvent de façon générique. Une bonne demande contient quatre ingrédients.",
      },
      {
        type: "illustration",
        id: "prompt-anatomy",
        caption: "Contexte, tâche, format, contraintes : quatre blocs qui transforment une réponse vague en réponse utile.",
      },
      { type: "example", label: "Trop vague", good: false, content: "Fais-moi un menu." },
      {
        type: "example",
        label: "Précis",
        good: true,
        content: "Je reçois 6 amis samedi, dont 2 végétariens. Propose un menu de 3 plats faciles, prêt en 1 heure, avec la liste de courses.",
      },
      {
        type: "keypoint",
        body: "La première réponse est un brouillon. Corrige, précise, redemande : « plus court », « plus simple », « sans viande »…",
      },
    ],
    questions: [
      {
        id: "premier-prompt:q1",
        type: "mcq",
        prompt: "Quelle demande obtiendra la réponse la plus utile ?",
        options: [
          { id: "a", text: "Parle-moi des volcans.", feedback: "Sans public ni format, la réponse sera générique." },
          { id: "b", text: "Explique les volcans à un enfant de 10 ans, en 5 phrases courtes, avec une comparaison du quotidien." },
          { id: "c", text: "VOLCANS !!! Vite.", feedback: "L'urgence n'aide pas l'IA à comprendre ce que tu veux." },
        ],
        answer: "b",
        explanation: "Elle précise le public (un enfant de 10 ans), le format (5 phrases) et une contrainte (une comparaison).",
      },
      {
        id: "premier-prompt:q2",
        type: "ordering",
        prompt: "Assemble la demande dans l'ordre recommandé : contexte, tâche, format, contraintes.",
        items: [
          { id: "a", text: "Je prépare un exposé de 5 minutes pour des collégiens." },
          { id: "b", text: "Explique comment fonctionne un volcan." },
          { id: "c", text: "Présente-le en 5 points courts." },
          { id: "d", text: "Utilise des mots simples, sans jargon." },
        ],
        answer: ["a", "b", "c", "d"],
        explanation: "D'abord la situation, puis ce que tu veux, sous quelle forme, et avec quelles limites.",
      },
      {
        id: "premier-prompt:q3",
        type: "true_false",
        statement: "Si la première réponse ne convient pas, mieux vaut toujours tout recommencer dans une nouvelle conversation.",
        answer: false,
        explanation: "Le plus souvent, il suffit de préciser dans la même conversation : l'IA garde le contexte de vos échanges.",
      },
      {
        id: "premier-prompt:q4",
        type: "fill_choice",
        prompt: "Complète la phrase.",
        sentence: "Préciser le ___ (liste, tableau, 3 phrases…) aide l'IA à répondre sous la bonne forme.",
        options: [
          { id: "a", text: "format" },
          { id: "b", text: "prix" },
          { id: "c", text: "mot de passe" },
        ],
        answer: "a",
        explanation: "Le format décrit la forme attendue de la réponse.",
      },
      {
        id: "premier-prompt:q5",
        type: "ai_analysis",
        prompt: "Pourquoi cette réponse risque-t-elle de ne pas t'aider ? Sélectionne tout ce qui s'applique.",
        userMessage: "Fais un texte sur le climat.",
        aiResponse: "Le climat est un sujet fondamental de notre époque. Depuis la révolution industrielle, les activités humaines ont profondément modifié… (800 mots plus tard) …En conclusion, chacun peut agir.",
        options: [
          { id: "a", text: "La demande ne dit ni pour qui, ni pourquoi, ni quelle longueur" },
          { id: "b", text: "Faute de contexte, l'IA a produit un texte générique" },
          { id: "c", text: "L'IA aurait dû refuser de répondre" },
          { id: "d", text: "Le climat est un sujet interdit" },
        ],
        answer: ["a", "b"],
        explanation: "La réponse n'est pas fausse, elle est générique. Avec un public, un objectif et une longueur, elle devient utilisable.",
      },
    ],
  },
  {
    id: "tuteur-pas-copieur",
    title: "L'IA comme tuteur, pas comme copieur",
    objective: "Utiliser l'IA pour comprendre et progresser, sans faire le travail à ta place.",
    level: 2,
    durationMin: 7,
    xp: 25,
    skills: ["Apprendre avec l'IA", "Respecter les règles de ton établissement"],
    prerequisites: ["hallucinations"],
    blocks: [
      {
        type: "text",
        title: "Faire faire ou apprendre",
        body: "Copier une réponse te fait gagner dix minutes et perdre l'apprentissage. Le même outil peut au contraire t'expliquer, te questionner et te corriger, comme un tuteur disponible à toute heure.",
      },
      {
        type: "illustration",
        id: "tutor-loop",
        caption: "La boucle du tuteur : comprendre, essayer seul, se faire corriger, réexpliquer avec ses mots.",
      },
      { type: "example", label: "Copieur", good: false, content: "Écris ma dissertation sur Candide." },
      {
        type: "example",
        label: "Tuteur",
        good: true,
        content: "Je dois écrire une dissertation sur Candide. Pose-moi des questions pour m'aider à trouver mon plan, sans l'écrire à ma place.",
      },
      {
        type: "text",
        title: "Les règles comptent",
        body: "Chaque établissement fixe ses règles sur l'IA. Rendre un travail rédigé par une IA sans le déclarer peut être traité comme du plagiat. En cas de doute, demande à ton enseignant.",
      },
      { type: "keypoint", body: "Si tu ne peux pas réexpliquer sans l'IA, tu n'as pas encore appris." },
    ],
    questions: [
      {
        id: "tuteur-pas-copieur:q1",
        type: "mcq",
        prompt: "Quelle demande t'aide vraiment à apprendre ?",
        options: [
          { id: "a", text: "Donne-moi les réponses de l'exercice 3.", feedback: "Tu auras les réponses, pas la méthode." },
          { id: "b", text: "Explique-moi la méthode sur un exemple différent, puis laisse-moi faire l'exercice 3." },
          { id: "c", text: "Réécris mon devoir pour qu'il soit parfait.", feedback: "Le devoir sera meilleur, toi non." },
        ],
        answer: "b",
        explanation: "Un exemple différent t'apprend la méthode sans te donner la réponse : c'est toi qui fais l'exercice.",
      },
      {
        id: "tuteur-pas-copieur:q2",
        type: "ordering",
        prompt: "Remets la boucle du tuteur dans l'ordre.",
        items: [
          { id: "a", text: "Demander une explication" },
          { id: "b", text: "Essayer seul un exercice" },
          { id: "c", text: "Faire corriger ton essai" },
          { id: "d", text: "Réexpliquer avec tes propres mots" },
        ],
        answer: ["a", "b", "c", "d"],
        explanation: "Comprendre, pratiquer, être corrigé, puis reformuler : la reformulation prouve que tu as compris.",
      },
      {
        id: "tuteur-pas-copieur:q3",
        type: "true_false",
        statement: "Rendre un devoir entièrement rédigé par une IA sans le dire peut être sanctionné comme du plagiat.",
        answer: true,
        explanation: "De nombreux établissements l'assimilent à de la fraude. Vérifie les règles du tien.",
      },
      {
        id: "tuteur-pas-copieur:q4",
        type: "fill_choice",
        prompt: "Complète le conseil.",
        sentence: "Demande à l'IA de te ___ plutôt que de te donner directement la réponse.",
        options: [
          { id: "a", text: "poser des questions" },
          { id: "b", text: "féliciter" },
          { id: "c", text: "traduire" },
        ],
        answer: "a",
        explanation: "Être questionné te force à réfléchir, comme avec un bon professeur.",
      },
      {
        id: "tuteur-pas-copieur:q5",
        type: "ai_analysis",
        prompt: "Qu'est-ce qui limite cet échange pour apprendre ? Sélectionne tout ce qui s'applique.",
        userMessage: "Résous l'exercice 4 de maths et donne juste le résultat.",
        aiResponse: "x = 7",
        options: [
          { id: "a", text: "Tu ne sais pas comment on arrive au résultat" },
          { id: "b", text: "Tu ne peux pas vérifier si c'est juste" },
          { id: "c", text: "La réponse est trop longue" },
          { id: "d", text: "L'IA a été impolie" },
        ],
        answer: ["a", "b"],
        explanation: "Sans la démarche, tu n'apprends rien et tu ne peux pas repérer une erreur éventuelle.",
      },
    ],
  },
  {
    id: "verifier-sources",
    title: "Vérifier une info avec des sources",
    objective: "Lire une réponse sourcée, ouvrir les liens et juger la fiabilité d'une source.",
    level: 2,
    durationMin: 7,
    xp: 25,
    skills: ["Lire une réponse sourcée", "Évaluer une source"],
    prerequisites: ["hallucinations"],
    volatile: { toolIds: ["perplexity"] },
    blocks: [
      {
        type: "text",
        title: "Des liens, pas des preuves",
        body: "Certains outils cherchent sur le web et ajoutent des liens numérotés à leur réponse. C'est un énorme progrès, à une condition : ouvrir les liens. Une source peut être peu fiable, ancienne, ou ne pas dire ce que le résumé affirme.",
      },
      { type: "tools", toolIds: ["perplexity"] },
      {
        type: "illustration",
        id: "review-checklist",
        caption: "Quatre questions à poser à chaque source.",
      },
      {
        type: "text",
        title: "Juger une source",
        body: "Qui publie ? (institution, journal, inconnu). Quand ? (une date récente compte pour les chiffres). Sur quoi s'appuie-t-elle ? (données, études, témoignages). Une deuxième source fiable dit-elle la même chose ?",
      },
      { type: "keypoint", body: "Une source citée n'est utile que si tu l'ouvres." },
    ],
    questions: [
      {
        id: "verifier-sources:q1",
        type: "ordering",
        prompt: "Remets dans l'ordre les étapes pour vérifier une info.",
        items: [
          { id: "a", text: "Lire la réponse de l'outil" },
          { id: "b", text: "Ouvrir les sources citées" },
          { id: "c", text: "Vérifier que la source dit bien ça" },
          { id: "d", text: "Recouper avec une deuxième source fiable" },
        ],
        answer: ["a", "b", "c", "d"],
        explanation: "La vérification se fait dans les sources elles-mêmes, puis par recoupement.",
      },
      {
        id: "verifier-sources:q2",
        type: "true_false",
        statement: "Si un outil cite un lien, l'information est forcément exacte.",
        answer: false,
        explanation: "Le lien peut être peu fiable, ou mal résumé par l'outil.",
      },
      {
        id: "verifier-sources:q3",
        type: "ranking",
        prompt: "Pour un exposé de SVT, classe ces sources de la plus à la moins fiable.",
        scale: ["La plus fiable", "La moins fiable"],
        items: [
          { id: "a", text: "Un article d'une revue scientifique" },
          { id: "b", text: "Une page pédagogique d'une université" },
          { id: "c", text: "Une vidéo anonyme sur un réseau social" },
        ],
        answer: ["a", "b", "c"],
        explanation: "Une revue scientifique est relue par des experts. Une université est une institution identifiée. Une vidéo anonyme n'offre aucune garantie.",
      },
      {
        id: "verifier-sources:q4",
        type: "mcq",
        prompt: "Quel critère compte le plus pour juger une source ?",
        options: [
          { id: "a", text: "Qui la publie et sur quelles preuves elle s'appuie" },
          { id: "b", text: "Sa place dans les résultats", feedback: "Être en haut des résultats ne garantit pas la fiabilité." },
          { id: "c", text: "Sa longueur", feedback: "Un texte long peut être faux, un texte court peut être solide." },
        ],
        answer: "a",
        explanation: "L'auteur et les preuves déterminent la confiance qu'on peut accorder.",
      },
      {
        id: "verifier-sources:q5",
        type: "ai_analysis",
        prompt: "Lis la réponse sourcée. Que faut-il remarquer ? Sélectionne tout ce qui s'applique.",
        userMessage: "Combien d'habitants compte Lyon ?",
        aiResponse: "Lyon compte environ 520 000 habitants [1].\n\n[1] blog-voyage-pas-cher.fr",
        options: [
          { id: "a", text: "La source est un blog, pas une source officielle comme l'Insee" },
          { id: "b", text: "Il faut vérifier de quelle année date ce chiffre" },
          { id: "c", text: "Le chiffre est forcément faux" },
          { id: "d", text: "Il ne faut jamais demander de chiffre à une IA" },
        ],
        answer: ["a", "b"],
        explanation: "Le chiffre peut être juste, mais la source est faible et non datée. L'Insee publie les chiffres officiels de population.",
      },
    ],
  },
  {
    id: "reviser-avec-ia",
    title: "Réviser avec l'IA",
    objective: "Transformer ton cours en quiz et en fiches, puis te tester activement.",
    level: 3,
    durationMin: 8,
    xp: 30,
    skills: ["Générer un quiz de révision", "Pratiquer le rappel actif"],
    prerequisites: ["tuteur-pas-copieur"],
    blocks: [
      {
        type: "text",
        title: "Se tester bat relire",
        body: "Relire ses notes donne une impression de maîtrise. Se tester (le rappel actif) ancre vraiment les connaissances, surtout si on espace les révisions dans le temps. C'est exactement ce que fait Gusgus avec tes révisions.",
      },
      {
        type: "illustration",
        id: "tutor-loop",
        caption: "Ton cours devient un quiz, tes erreurs deviennent la révision de demain.",
      },
      {
        type: "example",
        label: "Une demande de révision efficace",
        good: true,
        content: "Voici mon cours (collé ci-dessous). Pose-moi 10 questions, une par une. Attends ma réponse avant la suivante, corrige-moi et explique mes erreurs.",
      },
      {
        type: "keypoint",
        body: "Fournis ton propre cours : l'IA s'appuie dessus et invente beaucoup moins.",
      },
    ],
    questions: [
      {
        id: "reviser-avec-ia:q1",
        type: "mcq",
        prompt: "Pourquoi coller ton cours avant de demander un quiz ?",
        options: [
          { id: "a", text: "L'IA s'appuie sur ton contenu et invente moins" },
          { id: "b", text: "Pour que la réponse soit plus longue", feedback: "La longueur n'est pas le but." },
          { id: "c", text: "C'est obligatoire pour qu'elle réponde", feedback: "Non, mais sans ton cours elle improvise." },
        ],
        answer: "a",
        explanation: "Ton cours devient la référence : les questions collent à ce que tu dois savoir.",
      },
      {
        id: "reviser-avec-ia:q2",
        type: "true_false",
        statement: "Relire passivement ses notes est plus efficace que de se tester.",
        answer: false,
        explanation: "Le rappel actif est l'une des méthodes de révision les mieux étayées par la recherche.",
      },
      {
        id: "reviser-avec-ia:q3",
        type: "fill_choice",
        prompt: "Complète la demande.",
        sentence: "Pose-moi les questions ___ pour que je puisse répondre moi-même.",
        options: [
          { id: "a", text: "une par une" },
          { id: "b", text: "toutes d'un coup, avec les réponses" },
          { id: "c", text: "en anglais" },
        ],
        answer: "a",
        explanation: "Si les réponses s'affichent en même temps, tu ne te testes plus.",
      },
      {
        id: "reviser-avec-ia:q4",
        type: "ordering",
        prompt: "Remets une session de révision dans l'ordre.",
        items: [
          { id: "a", text: "Coller ton cours" },
          { id: "b", text: "Demander un quiz question par question" },
          { id: "c", text: "Répondre sans regarder tes notes" },
          { id: "d", text: "Revoir tes erreurs quelques jours plus tard" },
        ],
        answer: ["a", "b", "c", "d"],
        explanation: "Le dernier temps, revoir ses erreurs plus tard, c'est la répétition espacée.",
      },
      {
        id: "reviser-avec-ia:q5",
        type: "ai_analysis",
        prompt: "Cette fiche a été générée sans cours fourni. Que remarques-tu ? Sélectionne tout ce qui s'applique.",
        userMessage: "Fais-moi une fiche sur la Révolution française.",
        aiResponse: "• 1789 : prise de la Bastille\n• 1792 : proclamation de la République\n• 1804 : exécution de Louis XVI",
        options: [
          { id: "a", text: "Une date est fausse : Louis XVI a été exécuté en 1793" },
          { id: "b", text: "Sans cours fourni, chaque élément doit être vérifié" },
          { id: "c", text: "Une fiche ne doit jamais contenir de dates" },
          { id: "d", text: "Rien à signaler" },
        ],
        answer: ["a", "b"],
        explanation: "Louis XVI a été exécuté le 21 janvier 1793. En 1804, c'est le sacre de Napoléon. Une seule erreur suffit à fausser une révision.",
      },
    ],
  },
];
