import type { Lesson } from "../types";

export const workLessons: Lesson[] = [
  {
    id: "prompt-de-travail",
    title: "Le prompt de travail",
    objective: "Briefer l'IA comme un nouveau collègue : rôle, contexte, tâche, format, exemple.",
    level: 2,
    durationMin: 7,
    xp: 25,
    skills: ["Rédiger un brief pour l'IA", "Donner un exemple de référence"],
    prerequisites: ["comment-ecrit-un-chatbot"],
    blocks: [
      {
        type: "text",
        title: "Un collègue brillant, mais nouveau",
        body: "Imagine un collègue très compétent arrivé ce matin. Il ne connaît ni ton entreprise, ni tes clients, ni tes habitudes. Tout ce que tu ne précises pas, il le remplit par du générique. Un bon prompt de travail est un bon brief.",
      },
      {
        type: "illustration",
        id: "prompt-anatomy",
        caption: "Rôle et contexte d'abord, puis la tâche, puis le format et les contraintes.",
      },
      { type: "example", label: "Brief vague", good: false, content: "Écris un post LinkedIn sur notre produit." },
      {
        type: "example",
        label: "Brief utile",
        good: true,
        content: "Tu es chargé de communication d'une PME de logistique (40 salariés). Rédige un post LinkedIn annonçant notre suivi de colis en temps réel. Public : responsables achats. Ton sobre et concret. 120 mots maximum, un chiffre clé, pas d'emoji. Voici un post précédent qui a bien marché : […]",
      },
      { type: "keypoint", body: "Un bon exemple vaut mieux qu'une longue description du style attendu." },
    ],
    questions: [
      {
        id: "prompt-de-travail:q1",
        type: "ordering",
        prompt: "Remets les blocs d'un brief dans l'ordre recommandé.",
        items: [
          { id: "a", text: "Rôle : « Tu es chargé de communication… »" },
          { id: "b", text: "Contexte : l'entreprise, le public" },
          { id: "c", text: "Tâche : ce qu'il faut produire" },
          { id: "d", text: "Format et contraintes : longueur, ton, interdits" },
        ],
        answer: ["a", "b", "c", "d"],
        explanation: "On pose le cadre (rôle, contexte), puis on demande (tâche), puis on précise la forme.",
      },
      {
        id: "prompt-de-travail:q2",
        type: "mcq",
        prompt: "Quel ajout améliore le plus un prompt pour un email client ?",
        options: [
          { id: "a", text: "Un exemple d'email qui a bien fonctionné" },
          { id: "b", text: "« Fais de ton mieux »", feedback: "Ça ne donne aucune information utile." },
          { id: "c", text: "« C'est urgent »", feedback: "L'urgence ne change pas la qualité de la réponse." },
        ],
        answer: "a",
        explanation: "Un exemple montre le ton, la longueur et la structure attendus d'un seul coup.",
      },
      {
        id: "prompt-de-travail:q3",
        type: "fill_choice",
        prompt: "Complète le principe.",
        sentence: "Traite l'IA comme un ___ brillant qui ne connaît rien à ton entreprise.",
        options: [
          { id: "a", text: "nouveau collègue" },
          { id: "b", text: "moteur de recherche" },
          { id: "c", text: "client" },
        ],
        answer: "a",
        explanation: "Ce modèle mental pousse naturellement à donner le contexte nécessaire.",
      },
      {
        id: "prompt-de-travail:q4",
        type: "true_false",
        statement: "Demander plusieurs variantes, puis choisir et combiner, est une bonne pratique.",
        answer: true,
        explanation: "Trois propositions te montrent l'éventail des possibles et t'aident à préciser ce que tu veux.",
      },
      {
        id: "prompt-de-travail:q5",
        type: "ai_analysis",
        prompt: "Pourquoi ce résultat est-il peu utilisable ? Sélectionne tout ce qui s'applique.",
        userMessage: "Écris un email pour relancer un client.",
        aiResponse: "Objet : Relance\n\nBonjour [Nom],\n\nJe me permets de revenir vers vous concernant [sujet]. Pourriez-vous me faire un retour à votre convenance ?\n\nCordialement,\n[Signature]",
        options: [
          { id: "a", text: "Le prompt ne donne ni le contexte, ni l'historique, ni l'objectif" },
          { id: "b", text: "Résultat : un modèle générique rempli de trous" },
          { id: "c", text: "L'IA aurait dû envoyer l'email elle-même" },
          { id: "d", text: "Un email de relance ne doit pas avoir d'objet" },
        ],
        answer: ["a", "b"],
        explanation: "Sans savoir qui est le client, ce qui a été promis et ce que tu attends, l'IA ne peut produire qu'un gabarit.",
      },
    ],
  },
  {
    id: "donnees-confidentielles",
    title: "Données confidentielles au travail",
    objective: "Savoir quelles données ne jamais coller dans un outil grand public, et quoi faire à la place.",
    level: 2,
    durationMin: 7,
    xp: 25,
    skills: ["Classer les données selon leur sensibilité", "Anonymiser un document de travail"],
    prerequisites: ["prompt-de-travail"],
    blocks: [
      {
        type: "text",
        title: "Grand public ou entreprise",
        body: "Les versions grand public des assistants ne sont pas les offres « entreprise ». Ces dernières prévoient généralement des contrats sur la conservation et la non-utilisation des données pour l'entraînement. Ton entreprise a peut-être déjà choisi un outil : renseigne-toi avant tout usage professionnel.",
      },
      {
        type: "illustration",
        id: "data-flow",
        caption: "Un document collé quitte le périmètre de ton entreprise.",
      },
      {
        type: "text",
        title: "Ce qui ne sort pas",
        body: "Données personnelles de clients ou de collègues (protégées par le RGPD), secrets d'affaires, code source non public, chiffres financiers non publiés, contrats et documents juridiques.",
      },
      {
        type: "example",
        label: "Anonymiser",
        good: true,
        content: "« Le client Dupont SA, contact Mme Leroy, a un impayé de 12 400 € » devient « Le client A, contact X, a un impayé de N € ».",
      },
      { type: "keypoint", body: "En cas de doute : anonymise, résume, ou demande à ton responsable ou au DPO." },
    ],
    questions: [
      {
        id: "donnees-confidentielles:q1",
        type: "ranking",
        prompt: "Classe du plus au moins risqué à coller dans un chatbot grand public.",
        scale: ["Le plus risqué", "Le moins risqué"],
        items: [
          { id: "a", text: "Un fichier clients avec emails et téléphones" },
          { id: "b", text: "Un compte rendu de réunion interne anonymisé" },
          { id: "c", text: "Un article de presse déjà publié" },
        ],
        answer: ["a", "b", "c"],
        explanation: "Des données personnelles nominatives sont le cas le plus grave. Un document interne anonymisé reste interne. Un article public ne pose pas de problème.",
      },
      {
        id: "donnees-confidentielles:q2",
        type: "true_false",
        statement: "Les données personnelles de clients restent protégées par le RGPD, même quand tu utilises un outil d'IA.",
        answer: true,
        explanation: "Le RGPD s'applique quel que soit l'outil. Les transmettre à un service tiers sans base légale peut être une violation.",
      },
      {
        id: "donnees-confidentielles:q3",
        type: "mcq",
        prompt: "Ton entreprise n'a pas encore de règle sur l'IA. Le meilleur réflexe ?",
        options: [
          { id: "a", text: "Demander à ton responsable ou au DPO avant d'y mettre des données internes" },
          { id: "b", text: "Tout utiliser librement puisque rien n'est interdit", feedback: "L'absence de règle n'est pas une autorisation." },
          { id: "c", text: "Ne jamais utiliser l'IA", feedback: "Trop radical : des usages sans données sensibles restent possibles." },
        ],
        answer: "a",
        explanation: "Demander protège l'entreprise et toi, et fait souvent avancer la définition d'une règle commune.",
      },
      {
        id: "donnees-confidentielles:q4",
        type: "fill_choice",
        prompt: "Complète le réflexe.",
        sentence: "Avant de coller un document, remplace les noms de clients par des ___.",
        options: [
          { id: "a", text: "identifiants fictifs" },
          { id: "b", text: "emojis" },
          { id: "c", text: "majuscules" },
        ],
        answer: "a",
        explanation: "« Client A », « Client B » : l'IA peut travailler, personne n'est identifiable.",
      },
      {
        id: "donnees-confidentielles:q5",
        type: "ai_analysis",
        prompt: "Qu'est-ce qui pose problème ? Sélectionne tout ce qui s'applique.",
        userMessage: "Voici les salaires de mon équipe : Marie Dubois 52 k€, Karim Benali 48 k€, Léa Martin 45 k€. Aide-moi à préparer les augmentations.",
        aiResponse: "Bien sûr ! Pour Marie Dubois, une augmentation de 4 % porterait son salaire à 54 080 €…",
        options: [
          { id: "a", text: "Des données personnelles nominatives ont été partagées" },
          { id: "b", text: "Il aurait fallu anonymiser ou utiliser un outil validé par l'entreprise" },
          { id: "c", text: "L'IA a mal calculé l'augmentation" },
          { id: "d", text: "Aucun problème si l'outil est gratuit" },
        ],
        answer: ["a", "b"],
        explanation: "Le calcul est juste (52 000 × 1,04 = 54 080). Le problème, ce sont les salaires nominatifs envoyés à un service externe.",
      },
    ],
  },
  {
    id: "rediger-resumer",
    title: "Résumer et rédiger avec ChatGPT et Claude",
    objective: "Obtenir des résumés et des textes professionnels fiables, adaptés à leur lecteur.",
    level: 3,
    durationMin: 8,
    xp: 30,
    skills: ["Résumer un document long", "Adapter un texte à son lecteur"],
    prerequisites: ["donnees-confidentielles"],
    volatile: { toolIds: ["chatgpt", "claude"] },
    blocks: [
      {
        type: "text",
        title: "Un résumé a toujours un lecteur",
        body: "« Résume ce document » donne un résumé moyen. « Résume pour ma directrice, qui doit décider d'ici vendredi » donne un résumé utile. Précise le lecteur, l'objectif et ce qui compte le plus : décisions, chiffres, risques.",
      },
      { type: "tools", toolIds: ["chatgpt", "claude"] },
      {
        type: "example",
        label: "Demande de résumé",
        good: true,
        content: "Résume ce compte rendu pour mon directeur : 5 puces maximum, les décisions prises, les actions avec responsable et date. Signale tout ce qui est ambigu ou non décidé.",
      },
      {
        type: "illustration",
        id: "review-checklist",
        caption: "Avant d'envoyer, compare le résumé au document original.",
      },
      { type: "keypoint", body: "Relis toujours : un résumé peut omettre un point crucial, ou transformer une hypothèse en certitude." },
    ],
    questions: [
      {
        id: "rediger-resumer:q1",
        type: "mcq",
        prompt: "Quelle demande produira le résumé le plus utile ?",
        options: [
          { id: "a", text: "Résume ce document." , feedback: "Sans lecteur ni objectif, le résumé sera moyen." },
          { id: "b", text: "Résume ce document pour un client qui ne connaît pas le projet : 3 points clés et la prochaine étape attendue de sa part." },
          { id: "c", text: "Fais court.", feedback: "Court, mais pour qui et pour quoi ?" },
        ],
        answer: "b",
        explanation: "Lecteur, niveau de connaissance, format et action attendue : tout y est.",
      },
      {
        id: "rediger-resumer:q2",
        type: "true_false",
        statement: "Un résumé produit par l'IA peut omettre une information importante.",
        answer: true,
        explanation: "Résumer, c'est choisir. L'IA peut écarter justement le point qui compte pour toi.",
      },
      {
        id: "rediger-resumer:q3",
        type: "fill_choice",
        prompt: "Complète le conseil.",
        sentence: "Pour un résumé utile, précise ___ il est destiné.",
        options: [
          { id: "a", text: "à qui" },
          { id: "b", text: "dans quelle police" },
          { id: "c", text: "à quelle heure" },
        ],
        answer: "a",
        explanation: "Le lecteur détermine ce qui est important, le niveau de détail et le vocabulaire.",
      },
      {
        id: "rediger-resumer:q4",
        type: "ordering",
        prompt: "Rédiger un email délicat avec l'IA : remets les étapes dans l'ordre.",
        items: [
          { id: "a", text: "Expliquer la situation et l'objectif" },
          { id: "b", text: "Demander un premier jet" },
          { id: "c", text: "Dire ce qui ne va pas : ton, longueur, oublis" },
          { id: "d", text: "Relire et personnaliser avant l'envoi" },
        ],
        answer: ["a", "b", "c", "d"],
        explanation: "Contexte, brouillon, itération, puis ta relecture finale : c'est toi qui envoies.",
      },
      {
        id: "rediger-resumer:q5",
        type: "ai_analysis",
        prompt: "Le compte rendu disait : « Lancement reporté au 15 mars, à confirmer par Julie. » Que remarques-tu dans le résumé ?",
        userMessage: "Résume le compte rendu de réunion.",
        aiResponse: "Résumé : le lancement est fixé au 15 mars.",
        options: [
          { id: "a", text: "Une date « à confirmer » devient une certitude" },
          { id: "b", text: "Il oublie que Julie doit confirmer" },
          { id: "c", text: "Il est trop court pour être utile" },
          { id: "d", text: "Rien à signaler" },
        ],
        answer: ["a", "b"],
        explanation: "La nuance « à confirmer » et la responsable ont disparu. Ce type de glissement peut créer de vrais problèmes.",
      },
    ],
  },
  {
    id: "relire-ia",
    title: "Relire une réponse d'IA comme un pro",
    objective: "Auditer une réponse d'IA avec une grille : exactitude, preuves, complétude, ton, confidentialité.",
    level: 3,
    durationMin: 8,
    xp: 35,
    skills: ["Auditer une réponse d'IA", "Repérer les affirmations sans preuve"],
    prerequisites: ["rediger-resumer"],
    blocks: [
      {
        type: "text",
        title: "Tu signes, tu réponds",
        body: "Un texte produit par l'IA et envoyé sous ton nom engage ta responsabilité, pas celle de l'outil. Relire n'est pas une formalité : c'est la partie du travail que l'IA ne peut pas faire à ta place.",
      },
      {
        type: "illustration",
        id: "review-checklist",
        caption: "Une grille de relecture en quatre questions.",
      },
      {
        type: "example",
        label: "Le piège classique",
        good: false,
        content: "« Les ventes ont progressé de 30 %, grâce à la nouvelle campagne. » Deux affirmations : un calcul (vérifiable) et une cause (rien ne la prouve).",
      },
      {
        type: "text",
        title: "Faire relire l'IA par l'IA ?",
        body: "Demander « Relis ta réponse et liste ses faiblesses » est utile pour repérer des oublis. Mais l'IA peut confirmer ses propres erreurs : c'est un complément, pas un remplacement.",
      },
      { type: "keypoint", body: "Vérifie chaque chiffre, et méfie-toi de chaque « grâce à » et « à cause de »." },
    ],
    questions: [
      {
        id: "relire-ia:q1",
        type: "ai_analysis",
        prompt: "Relis cette analyse. Sélectionne tous les problèmes.",
        userMessage: "Compare nos ventes : T1 = 120 k€, T2 = 150 k€.",
        aiResponse: "Les ventes ont progressé de 30 % entre T1 et T2, principalement grâce à la nouvelle campagne marketing.",
        options: [
          { id: "a", text: "Le calcul est faux : +30 k€ sur 120 k€, c'est +25 %" },
          { id: "b", text: "La cause « campagne marketing » ne s'appuie sur aucune donnée fournie" },
          { id: "c", text: "La réponse devrait être plus longue" },
          { id: "d", text: "Les montants devraient être en dollars" },
        ],
        answer: ["a", "b"],
        explanation: "(150 − 120) / 120 = 25 %. Quant à la campagne, l'IA l'a inventée comme explication plausible.",
      },
      {
        id: "relire-ia:q2",
        type: "ranking",
        prompt: "Dans un rapport envoyé à un client, classe ces erreurs de la plus à la moins grave.",
        scale: ["La plus grave", "La moins grave"],
        items: [
          { id: "a", text: "Un chiffre faux" },
          { id: "b", text: "Une faute de frappe" },
          { id: "c", text: "Une mise en page imparfaite" },
        ],
        answer: ["a", "b", "c"],
        explanation: "Un chiffre faux peut entraîner une mauvaise décision. Les deux autres touchent l'image, pas le fond.",
      },
      {
        id: "relire-ia:q3",
        type: "true_false",
        statement: "Demander à l'IA de relire sa propre réponse remplace ta relecture.",
        answer: false,
        explanation: "C'est un complément utile, mais l'IA peut confirmer ses propres erreurs.",
      },
      {
        id: "relire-ia:q4",
        type: "mcq",
        prompt: "Qui est responsable d'un email envoyé avec un texte généré par IA ?",
        options: [
          { id: "a", text: "Toi, la personne qui l'envoie" },
          { id: "b", text: "L'éditeur de l'outil", feedback: "Les conditions d'utilisation des outils te laissent la responsabilité de l'usage." },
          { id: "c", text: "Personne", feedback: "Il y a toujours quelqu'un qui envoie." },
        ],
        answer: "a",
        explanation: "L'IA est un outil. Ce que tu envoies t'engage.",
      },
      {
        id: "relire-ia:q5",
        type: "fill_choice",
        prompt: "Complète la phrase.",
        sentence: "Une explication causale (« grâce à… ») sans données pour l'appuyer est une ___ à vérifier.",
        options: [
          { id: "a", text: "hypothèse" },
          { id: "b", text: "preuve" },
          { id: "c", text: "conclusion certaine" },
        ],
        answer: "a",
        explanation: "Tant qu'aucune donnée ne l'appuie, une cause proposée par l'IA reste une hypothèse.",
      },
    ],
  },
];
